// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.1
// source: neighborhood/neighborhood.proto

package neighborhood

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Neighborhood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"title",validate:"required"
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title" validate:"required"`
	// @inject_tag: json:"name",validate:"alpha,required"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name" validate:"alpha,required"`
	// @inject_tag: json:"province",validate:"alphanum,required"
	Province string `protobuf:"bytes,3,opt,name=province,proto3" json:"province" validate:"alphanum,required"`
	// @inject_tag: json:"city",validate:"alphanum,required"
	City string `protobuf:"bytes,4,opt,name=city,proto3" json:"city" validate:"alphanum,required"`
}

func (x *Neighborhood) Reset() {
	*x = Neighborhood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighborhood_neighborhood_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Neighborhood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Neighborhood) ProtoMessage() {}

func (x *Neighborhood) ProtoReflect() protoreflect.Message {
	mi := &file_neighborhood_neighborhood_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Neighborhood.ProtoReflect.Descriptor instead.
func (*Neighborhood) Descriptor() ([]byte, []int) {
	return file_neighborhood_neighborhood_proto_rawDescGZIP(), []int{0}
}

func (x *Neighborhood) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Neighborhood) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Neighborhood) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Neighborhood) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type NeighborhoodFull struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Province *Area  `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	City     *Area  `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *NeighborhoodFull) Reset() {
	*x = NeighborhoodFull{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighborhood_neighborhood_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NeighborhoodFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborhoodFull) ProtoMessage() {}

func (x *NeighborhoodFull) ProtoReflect() protoreflect.Message {
	mi := &file_neighborhood_neighborhood_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborhoodFull.ProtoReflect.Descriptor instead.
func (*NeighborhoodFull) Descriptor() ([]byte, []int) {
	return file_neighborhood_neighborhood_proto_rawDescGZIP(), []int{1}
}

func (x *NeighborhoodFull) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NeighborhoodFull) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NeighborhoodFull) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NeighborhoodFull) GetProvince() *Area {
	if x != nil {
		return x.Province
	}
	return nil
}

func (x *NeighborhoodFull) GetCity() *Area {
	if x != nil {
		return x.City
	}
	return nil
}

type Area struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Area) Reset() {
	*x = Area{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighborhood_neighborhood_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Area) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Area) ProtoMessage() {}

func (x *Area) ProtoReflect() protoreflect.Message {
	mi := &file_neighborhood_neighborhood_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Area.ProtoReflect.Descriptor instead.
func (*Area) Descriptor() ([]byte, []int) {
	return file_neighborhood_neighborhood_proto_rawDescGZIP(), []int{2}
}

func (x *Area) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Area) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Area) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RequestDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id",validate:"required"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" validate:"required"`
}

func (x *RequestDetails) Reset() {
	*x = RequestDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighborhood_neighborhood_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDetails) ProtoMessage() {}

func (x *RequestDetails) ProtoReflect() protoreflect.Message {
	mi := &file_neighborhood_neighborhood_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDetails.ProtoReflect.Descriptor instead.
func (*RequestDetails) Descriptor() ([]byte, []int) {
	return file_neighborhood_neighborhood_proto_rawDescGZIP(), []int{3}
}

func (x *RequestDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResponseDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Neighborhood *Neighborhood `protobuf:"bytes,2,opt,name=neighborhood,proto3" json:"neighborhood,omitempty"`
	Creator      string        `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (x *ResponseDetails) Reset() {
	*x = ResponseDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighborhood_neighborhood_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDetails) ProtoMessage() {}

func (x *ResponseDetails) ProtoReflect() protoreflect.Message {
	mi := &file_neighborhood_neighborhood_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDetails.ProtoReflect.Descriptor instead.
func (*ResponseDetails) Descriptor() ([]byte, []int) {
	return file_neighborhood_neighborhood_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ResponseDetails) GetNeighborhood() *Neighborhood {
	if x != nil {
		return x.Neighborhood
	}
	return nil
}

func (x *ResponseDetails) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

type RequestCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"neighborhood",validate:"required"
	Neighborhood *Neighborhood `protobuf:"bytes,1,opt,name=neighborhood,proto3" json:"neighborhood" validate:"required"`
	// @inject_tag: json:"-"
	Creator string `protobuf:"bytes,2,opt,name=creator,proto3" json:"-"`
}

func (x *RequestCreate) Reset() {
	*x = RequestCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighborhood_neighborhood_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreate) ProtoMessage() {}

func (x *RequestCreate) ProtoReflect() protoreflect.Message {
	mi := &file_neighborhood_neighborhood_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreate.ProtoReflect.Descriptor instead.
func (*RequestCreate) Descriptor() ([]byte, []int) {
	return file_neighborhood_neighborhood_proto_rawDescGZIP(), []int{5}
}

func (x *RequestCreate) GetNeighborhood() *Neighborhood {
	if x != nil {
		return x.Neighborhood
	}
	return nil
}

func (x *RequestCreate) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

type RequestCheckExistByProvinceIdAndCityId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Neighborhood *Neighborhood `protobuf:"bytes,1,opt,name=neighborhood,proto3" json:"neighborhood,omitempty"`
}

func (x *RequestCheckExistByProvinceIdAndCityId) Reset() {
	*x = RequestCheckExistByProvinceIdAndCityId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighborhood_neighborhood_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCheckExistByProvinceIdAndCityId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCheckExistByProvinceIdAndCityId) ProtoMessage() {}

func (x *RequestCheckExistByProvinceIdAndCityId) ProtoReflect() protoreflect.Message {
	mi := &file_neighborhood_neighborhood_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCheckExistByProvinceIdAndCityId.ProtoReflect.Descriptor instead.
func (*RequestCheckExistByProvinceIdAndCityId) Descriptor() ([]byte, []int) {
	return file_neighborhood_neighborhood_proto_rawDescGZIP(), []int{6}
}

func (x *RequestCheckExistByProvinceIdAndCityId) GetNeighborhood() *Neighborhood {
	if x != nil {
		return x.Neighborhood
	}
	return nil
}

type ResponseCheckExistByProvinceIdAndCityId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsExist bool `protobuf:"varint,1,opt,name=isExist,proto3" json:"isExist,omitempty"`
}

func (x *ResponseCheckExistByProvinceIdAndCityId) Reset() {
	*x = ResponseCheckExistByProvinceIdAndCityId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighborhood_neighborhood_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCheckExistByProvinceIdAndCityId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCheckExistByProvinceIdAndCityId) ProtoMessage() {}

func (x *ResponseCheckExistByProvinceIdAndCityId) ProtoReflect() protoreflect.Message {
	mi := &file_neighborhood_neighborhood_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCheckExistByProvinceIdAndCityId.ProtoReflect.Descriptor instead.
func (*ResponseCheckExistByProvinceIdAndCityId) Descriptor() ([]byte, []int) {
	return file_neighborhood_neighborhood_proto_rawDescGZIP(), []int{7}
}

func (x *ResponseCheckExistByProvinceIdAndCityId) GetIsExist() bool {
	if x != nil {
		return x.IsExist
	}
	return false
}

type RequestCheckValidNeighborhood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Neighborhood string `protobuf:"bytes,1,opt,name=neighborhood,proto3" json:"neighborhood,omitempty"`
	Province     string `protobuf:"bytes,2,opt,name=province,proto3" json:"province,omitempty"`
	City         string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
}

func (x *RequestCheckValidNeighborhood) Reset() {
	*x = RequestCheckValidNeighborhood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighborhood_neighborhood_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCheckValidNeighborhood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCheckValidNeighborhood) ProtoMessage() {}

func (x *RequestCheckValidNeighborhood) ProtoReflect() protoreflect.Message {
	mi := &file_neighborhood_neighborhood_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCheckValidNeighborhood.ProtoReflect.Descriptor instead.
func (*RequestCheckValidNeighborhood) Descriptor() ([]byte, []int) {
	return file_neighborhood_neighborhood_proto_rawDescGZIP(), []int{8}
}

func (x *RequestCheckValidNeighborhood) GetNeighborhood() string {
	if x != nil {
		return x.Neighborhood
	}
	return ""
}

func (x *RequestCheckValidNeighborhood) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *RequestCheckValidNeighborhood) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type ResponseCheckValidNeighborhood struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid bool `protobuf:"varint,1,opt,name=isValid,proto3" json:"isValid,omitempty"`
}

func (x *ResponseCheckValidNeighborhood) Reset() {
	*x = ResponseCheckValidNeighborhood{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighborhood_neighborhood_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCheckValidNeighborhood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCheckValidNeighborhood) ProtoMessage() {}

func (x *ResponseCheckValidNeighborhood) ProtoReflect() protoreflect.Message {
	mi := &file_neighborhood_neighborhood_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCheckValidNeighborhood.ProtoReflect.Descriptor instead.
func (*ResponseCheckValidNeighborhood) Descriptor() ([]byte, []int) {
	return file_neighborhood_neighborhood_proto_rawDescGZIP(), []int{9}
}

func (x *ResponseCheckValidNeighborhood) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type RequestList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"count",validate:"number,min=10,required"
	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count" validate:"number,min=10,required"`
	// @inject_tag: json:"page",validate:"number,min=1,required"
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page" validate:"number,min=1,required"`
}

func (x *RequestList) Reset() {
	*x = RequestList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighborhood_neighborhood_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestList) ProtoMessage() {}

func (x *RequestList) ProtoReflect() protoreflect.Message {
	mi := &file_neighborhood_neighborhood_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestList.ProtoReflect.Descriptor instead.
func (*RequestList) Descriptor() ([]byte, []int) {
	return file_neighborhood_neighborhood_proto_rawDescGZIP(), []int{10}
}

func (x *RequestList) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RequestList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ResponseList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Neighborhoods []*NeighborhoodFull `protobuf:"bytes,1,rep,name=neighborhoods,proto3" json:"neighborhoods,omitempty"`
}

func (x *ResponseList) Reset() {
	*x = ResponseList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_neighborhood_neighborhood_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseList) ProtoMessage() {}

func (x *ResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_neighborhood_neighborhood_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseList.ProtoReflect.Descriptor instead.
func (*ResponseList) Descriptor() ([]byte, []int) {
	return file_neighborhood_neighborhood_proto_rawDescGZIP(), []int{11}
}

func (x *ResponseList) GetNeighborhoods() []*NeighborhoodFull {
	if x != nil {
		return x.Neighborhoods
	}
	return nil
}

var File_neighborhood_neighborhood_proto protoreflect.FileDescriptor

var file_neighborhood_neighborhood_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2f, 0x6e,
	0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x22,
	0x68, 0x0a, 0x0c, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x22, 0xa4, 0x01, 0x0a, 0x10, 0x4e, 0x65,
	0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x46, 0x75, 0x6c, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x65, 0x69,
	0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x52, 0x08,
	0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f,
	0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x22, 0x40, 0x0a, 0x04, 0x41, 0x72, 0x65, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x7b, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3e, 0x0a, 0x0c, 0x6e, 0x65, 0x69, 0x67, 0x68,
	0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x4e, 0x65, 0x69,
	0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x52, 0x0c, 0x6e, 0x65, 0x69, 0x67, 0x68,
	0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x22, 0x69, 0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f,
	0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6e, 0x65, 0x69, 0x67, 0x68,
	0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72,
	0x68, 0x6f, 0x6f, 0x64, 0x52, 0x0c, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f,
	0x6f, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x68, 0x0a, 0x26,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x69, 0x73,
	0x74, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x41, 0x6e, 0x64,
	0x43, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x3e, 0x0a, 0x0c, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62,
	0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6e,
	0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x4e, 0x65, 0x69, 0x67,
	0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x52, 0x0c, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62,
	0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x22, 0x43, 0x0a, 0x27, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x69, 0x73, 0x74, 0x42, 0x79, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x41, 0x6e, 0x64, 0x43, 0x69, 0x74, 0x79, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x22, 0x73, 0x0a, 0x1d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x22, 0x3a, 0x0a, 0x1e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f,
	0x6f, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x0b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x54, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x44, 0x0a, 0x0d, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f,
	0x72, 0x68, 0x6f, 0x6f, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6e,
	0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x4e, 0x65, 0x69, 0x67,
	0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x46, 0x75, 0x6c, 0x6c, 0x52, 0x0d, 0x6e, 0x65,
	0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x73, 0x32, 0xa8, 0x03, 0x0a, 0x13,
	0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e,
	0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x1a, 0x1d, 0x2e, 0x6e, 0x65, 0x69,
	0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x00, 0x12, 0x90, 0x01, 0x0a, 0x1f,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x69, 0x73, 0x74, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x41, 0x6e, 0x64, 0x43, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x34, 0x2e, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x42, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x41, 0x6e, 0x64, 0x43,
	0x69, 0x74, 0x79, 0x49, 0x64, 0x1a, 0x35, 0x2e, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72,
	0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x45, 0x78, 0x69, 0x73, 0x74, 0x42, 0x79, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63,
	0x65, 0x49, 0x64, 0x41, 0x6e, 0x64, 0x43, 0x69, 0x74, 0x79, 0x49, 0x64, 0x22, 0x00, 0x12, 0x75,
	0x0a, 0x16, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x4e, 0x65, 0x69, 0x67,
	0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x12, 0x2b, 0x2e, 0x6e, 0x65, 0x69, 0x67, 0x68,
	0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f,
	0x72, 0x68, 0x6f, 0x6f, 0x64, 0x1a, 0x2c, 0x2e, 0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72,
	0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68,
	0x6f, 0x6f, 0x64, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e,
	0x6e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6e, 0x65, 0x69, 0x67, 0x68,
	0x62, 0x6f, 0x72, 0x68, 0x6f, 0x6f, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_neighborhood_neighborhood_proto_rawDescOnce sync.Once
	file_neighborhood_neighborhood_proto_rawDescData = file_neighborhood_neighborhood_proto_rawDesc
)

func file_neighborhood_neighborhood_proto_rawDescGZIP() []byte {
	file_neighborhood_neighborhood_proto_rawDescOnce.Do(func() {
		file_neighborhood_neighborhood_proto_rawDescData = protoimpl.X.CompressGZIP(file_neighborhood_neighborhood_proto_rawDescData)
	})
	return file_neighborhood_neighborhood_proto_rawDescData
}

var file_neighborhood_neighborhood_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_neighborhood_neighborhood_proto_goTypes = []interface{}{
	(*Neighborhood)(nil),                            // 0: neighborhood.Neighborhood
	(*NeighborhoodFull)(nil),                        // 1: neighborhood.NeighborhoodFull
	(*Area)(nil),                                    // 2: neighborhood.Area
	(*RequestDetails)(nil),                          // 3: neighborhood.RequestDetails
	(*ResponseDetails)(nil),                         // 4: neighborhood.ResponseDetails
	(*RequestCreate)(nil),                           // 5: neighborhood.RequestCreate
	(*RequestCheckExistByProvinceIdAndCityId)(nil),  // 6: neighborhood.RequestCheckExistByProvinceIdAndCityId
	(*ResponseCheckExistByProvinceIdAndCityId)(nil), // 7: neighborhood.ResponseCheckExistByProvinceIdAndCityId
	(*RequestCheckValidNeighborhood)(nil),           // 8: neighborhood.RequestCheckValidNeighborhood
	(*ResponseCheckValidNeighborhood)(nil),          // 9: neighborhood.ResponseCheckValidNeighborhood
	(*RequestList)(nil),                             // 10: neighborhood.RequestList
	(*ResponseList)(nil),                            // 11: neighborhood.ResponseList
}
var file_neighborhood_neighborhood_proto_depIdxs = []int32{
	2,  // 0: neighborhood.NeighborhoodFull.province:type_name -> neighborhood.Area
	2,  // 1: neighborhood.NeighborhoodFull.city:type_name -> neighborhood.Area
	0,  // 2: neighborhood.ResponseDetails.neighborhood:type_name -> neighborhood.Neighborhood
	0,  // 3: neighborhood.RequestCreate.neighborhood:type_name -> neighborhood.Neighborhood
	0,  // 4: neighborhood.RequestCheckExistByProvinceIdAndCityId.neighborhood:type_name -> neighborhood.Neighborhood
	1,  // 5: neighborhood.ResponseList.neighborhoods:type_name -> neighborhood.NeighborhoodFull
	5,  // 6: neighborhood.neighborhoodService.Create:input_type -> neighborhood.RequestCreate
	6,  // 7: neighborhood.neighborhoodService.CheckExistByProvinceIdAndCityId:input_type -> neighborhood.RequestCheckExistByProvinceIdAndCityId
	8,  // 8: neighborhood.neighborhoodService.CheckValidNeighborhood:input_type -> neighborhood.RequestCheckValidNeighborhood
	10, // 9: neighborhood.neighborhoodService.list:input_type -> neighborhood.RequestList
	4,  // 10: neighborhood.neighborhoodService.Create:output_type -> neighborhood.ResponseDetails
	7,  // 11: neighborhood.neighborhoodService.CheckExistByProvinceIdAndCityId:output_type -> neighborhood.ResponseCheckExistByProvinceIdAndCityId
	9,  // 12: neighborhood.neighborhoodService.CheckValidNeighborhood:output_type -> neighborhood.ResponseCheckValidNeighborhood
	11, // 13: neighborhood.neighborhoodService.list:output_type -> neighborhood.ResponseList
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_neighborhood_neighborhood_proto_init() }
func file_neighborhood_neighborhood_proto_init() {
	if File_neighborhood_neighborhood_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_neighborhood_neighborhood_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Neighborhood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighborhood_neighborhood_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NeighborhoodFull); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighborhood_neighborhood_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Area); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighborhood_neighborhood_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighborhood_neighborhood_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighborhood_neighborhood_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighborhood_neighborhood_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCheckExistByProvinceIdAndCityId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighborhood_neighborhood_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCheckExistByProvinceIdAndCityId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighborhood_neighborhood_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCheckValidNeighborhood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighborhood_neighborhood_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCheckValidNeighborhood); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighborhood_neighborhood_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_neighborhood_neighborhood_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_neighborhood_neighborhood_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neighborhood_neighborhood_proto_goTypes,
		DependencyIndexes: file_neighborhood_neighborhood_proto_depIdxs,
		MessageInfos:      file_neighborhood_neighborhood_proto_msgTypes,
	}.Build()
	File_neighborhood_neighborhood_proto = out.File
	file_neighborhood_neighborhood_proto_rawDesc = nil
	file_neighborhood_neighborhood_proto_goTypes = nil
	file_neighborhood_neighborhood_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NeighborhoodServiceClient is the client API for NeighborhoodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NeighborhoodServiceClient interface {
	Create(ctx context.Context, in *RequestCreate, opts ...grpc.CallOption) (*ResponseDetails, error)
	CheckExistByProvinceIdAndCityId(ctx context.Context, in *RequestCheckExistByProvinceIdAndCityId, opts ...grpc.CallOption) (*ResponseCheckExistByProvinceIdAndCityId, error)
	CheckValidNeighborhood(ctx context.Context, in *RequestCheckValidNeighborhood, opts ...grpc.CallOption) (*ResponseCheckValidNeighborhood, error)
	List(ctx context.Context, in *RequestList, opts ...grpc.CallOption) (*ResponseList, error)
}

type neighborhoodServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNeighborhoodServiceClient(cc grpc.ClientConnInterface) NeighborhoodServiceClient {
	return &neighborhoodServiceClient{cc}
}

func (c *neighborhoodServiceClient) Create(ctx context.Context, in *RequestCreate, opts ...grpc.CallOption) (*ResponseDetails, error) {
	out := new(ResponseDetails)
	err := c.cc.Invoke(ctx, "/neighborhood.neighborhoodService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neighborhoodServiceClient) CheckExistByProvinceIdAndCityId(ctx context.Context, in *RequestCheckExistByProvinceIdAndCityId, opts ...grpc.CallOption) (*ResponseCheckExistByProvinceIdAndCityId, error) {
	out := new(ResponseCheckExistByProvinceIdAndCityId)
	err := c.cc.Invoke(ctx, "/neighborhood.neighborhoodService/CheckExistByProvinceIdAndCityId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neighborhoodServiceClient) CheckValidNeighborhood(ctx context.Context, in *RequestCheckValidNeighborhood, opts ...grpc.CallOption) (*ResponseCheckValidNeighborhood, error) {
	out := new(ResponseCheckValidNeighborhood)
	err := c.cc.Invoke(ctx, "/neighborhood.neighborhoodService/CheckValidNeighborhood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neighborhoodServiceClient) List(ctx context.Context, in *RequestList, opts ...grpc.CallOption) (*ResponseList, error) {
	out := new(ResponseList)
	err := c.cc.Invoke(ctx, "/neighborhood.neighborhoodService/list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NeighborhoodServiceServer is the server API for NeighborhoodService service.
type NeighborhoodServiceServer interface {
	Create(context.Context, *RequestCreate) (*ResponseDetails, error)
	CheckExistByProvinceIdAndCityId(context.Context, *RequestCheckExistByProvinceIdAndCityId) (*ResponseCheckExistByProvinceIdAndCityId, error)
	CheckValidNeighborhood(context.Context, *RequestCheckValidNeighborhood) (*ResponseCheckValidNeighborhood, error)
	List(context.Context, *RequestList) (*ResponseList, error)
}

// UnimplementedNeighborhoodServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNeighborhoodServiceServer struct {
}

func (*UnimplementedNeighborhoodServiceServer) Create(context.Context, *RequestCreate) (*ResponseDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedNeighborhoodServiceServer) CheckExistByProvinceIdAndCityId(context.Context, *RequestCheckExistByProvinceIdAndCityId) (*ResponseCheckExistByProvinceIdAndCityId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckExistByProvinceIdAndCityId not implemented")
}
func (*UnimplementedNeighborhoodServiceServer) CheckValidNeighborhood(context.Context, *RequestCheckValidNeighborhood) (*ResponseCheckValidNeighborhood, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckValidNeighborhood not implemented")
}
func (*UnimplementedNeighborhoodServiceServer) List(context.Context, *RequestList) (*ResponseList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterNeighborhoodServiceServer(s *grpc.Server, srv NeighborhoodServiceServer) {
	s.RegisterService(&_NeighborhoodService_serviceDesc, srv)
}

func _NeighborhoodService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCreate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NeighborhoodServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/neighborhood.neighborhoodService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NeighborhoodServiceServer).Create(ctx, req.(*RequestCreate))
	}
	return interceptor(ctx, in, info, handler)
}

func _NeighborhoodService_CheckExistByProvinceIdAndCityId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCheckExistByProvinceIdAndCityId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NeighborhoodServiceServer).CheckExistByProvinceIdAndCityId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/neighborhood.neighborhoodService/CheckExistByProvinceIdAndCityId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NeighborhoodServiceServer).CheckExistByProvinceIdAndCityId(ctx, req.(*RequestCheckExistByProvinceIdAndCityId))
	}
	return interceptor(ctx, in, info, handler)
}

func _NeighborhoodService_CheckValidNeighborhood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCheckValidNeighborhood)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NeighborhoodServiceServer).CheckValidNeighborhood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/neighborhood.neighborhoodService/CheckValidNeighborhood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NeighborhoodServiceServer).CheckValidNeighborhood(ctx, req.(*RequestCheckValidNeighborhood))
	}
	return interceptor(ctx, in, info, handler)
}

func _NeighborhoodService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NeighborhoodServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/neighborhood.neighborhoodService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NeighborhoodServiceServer).List(ctx, req.(*RequestList))
	}
	return interceptor(ctx, in, info, handler)
}

var _NeighborhoodService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "neighborhood.neighborhoodService",
	HandlerType: (*NeighborhoodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _NeighborhoodService_Create_Handler,
		},
		{
			MethodName: "CheckExistByProvinceIdAndCityId",
			Handler:    _NeighborhoodService_CheckExistByProvinceIdAndCityId_Handler,
		},
		{
			MethodName: "CheckValidNeighborhood",
			Handler:    _NeighborhoodService_CheckValidNeighborhood_Handler,
		},
		{
			MethodName: "list",
			Handler:    _NeighborhoodService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "neighborhood/neighborhood.proto",
}
